#!/bin/bash
  # all I did here was add a comment -cody
  # Config selection
  echo 'Select a config:'
  echo '1: root@host1:/'
  echo '2: root@host2:/'
  read input
  case $input in
    1)
      folder='host1'
      ssh_string='root@host1:/';;

    2)
      folder='host2'
      ssh_string='root@host2:/';;
  esac

  # Function selection
  echo 'Select a function:'
  echo '1: mount'
  echo '2: unmount'
  echo '3: remount'
  read input
  case $input in
    1)
      if [ ! -d "/media/$USER/$folder" ]; then
        # Create mounting folder
	command="mkdir /media/$USER/$folder;"
      fi
      command="$command sshfs -o allow_other $ssh_string /media/$USER/$folder";;

    2)
      command="fusermount -u /media/$USER/$folder";;

    3)
      command="fusermount -u /media/$USER/$folder;
      sshfs -o allow_other $ssh_string /media/$USER/$folder";;
  esac

  eval $command;
